window.EBINA_DATA = {
  site: {
    name: "海老名びより",
    tagline: "海老名の変化を、知る。追う。参加する。",
    lastUpdated: "2026年7月11日",
  },
  categories: [
    { id: "development", label: "開発・まちづくり", icon: "建" },
    { id: "shops", label: "開店・閉店", icon: "店" },
    { id: "government", label: "市政・暮らし", icon: "暮" },
    { id: "transport", label: "交通", icon: "交" },
    { id: "events", label: "イベント", icon: "催" },
    { id: "welfare", label: "子育て・福祉", icon: "育" },
    { id: "disaster", label: "防災", icon: "防" },
  ],
  news: [
    {
      id: "station-east-passage",
      category: "development",
      title: "【デモ】海老名駅東口周辺で歩行者動線の改善案を公表",
      excerpt: "駅前の回遊性向上を想定した架空の整備案について、確認ポイントをまとめました。",
      publishedAt: "2026年7月10日",
      checkedAt: "2026年7月11日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      important: true,
      body: [
        "これはサイトの表示・機能確認を目的とした架空のデモ記事です。実在する行政計画や発表を示すものではありません。",
        "デモ設定では、駅東口周辺の歩行者動線について検討資料が公表された想定です。今後は、対象範囲、工事時期、バリアフリーへの配慮などを継続確認する構成を想定しています。",
      ],
    },
    {
      id: "community-bus-trial",
      category: "transport",
      title: "【デモ】地域交通の実証運行、秋から3か月間を想定",
      excerpt: "移動手段の選択肢を増やす架空の実証事業。対象地域と利用方法を整理します。",
      publishedAt: "2026年7月9日",
      checkedAt: "2026年7月11日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      important: true,
      body: ["この記事は架空のデモ情報です。実証運行の事実はありません。", "本番運用では、公式発表へのリンク、運行期間、停留所、運賃、検証結果を分けて掲載します。"],
    },
    {
      id: "summer-heat-shelter",
      category: "welfare",
      title: "【デモ】夏の休憩スポット、市内12か所に設置という想定記事",
      excerpt: "暑さを避けて休める場所について、利用時間や設備を確認するデモ記事です。",
      publishedAt: "2026年7月8日",
      checkedAt: "2026年7月10日",
      sourceType: "独自確認",
      source: "デモ取材メモ（実在しません）",
      important: true,
      body: ["この記事は機能確認用の架空情報です。", "実際の緊急情報や暑さ対策については、海老名市などの公式情報をご確認ください。"],
    },
    {
      id: "new-cafe-west",
      category: "shops",
      title: "【デモ】駅西口エリアに地域交流カフェが開店予定",
      excerpt: "子ども連れでも利用しやすいという架空店舗の情報を、店舗公式発表の形式で掲載。",
      publishedAt: "2026年7月7日",
      checkedAt: "2026年7月9日",
      sourceType: "企業・店舗公式",
      source: "デモ店舗のお知らせ（実在しません）",
      body: ["店舗・開店情報を想定した架空のデモ記事です。", "本番では店舗公式サイトや現地掲示など、確認した情報源を明記します。"],
    },
    {
      id: "park-renewal-survey",
      category: "development",
      title: "【デモ】近隣公園の更新に向けた利用者アンケートを開始",
      excerpt: "遊具、休憩場所、防災機能に関する架空アンケートの募集要項です。",
      publishedAt: "2026年7月6日",
      checkedAt: "2026年7月8日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      body: ["この募集は実在しないデモです。", "将来の本番記事では、募集期間、回答方法、結果の公開予定を追跡します。"],
    },
    {
      id: "river-drill",
      category: "disaster",
      title: "【デモ】河川周辺地域で避難行動を確認する訓練を計画",
      excerpt: "水害時の行動を地域単位で確認する想定訓練についてまとめています。",
      publishedAt: "2026年7月5日",
      checkedAt: "2026年7月8日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      body: ["これは架空の訓練情報です。実際の防災情報ではありません。", "緊急時は海老名市や気象庁などの公式情報を優先してください。"],
    },
    {
      id: "library-evening",
      category: "events",
      title: "【デモ】夏休み期間に図書イベントを開催する想定",
      excerpt: "夕方から親子で参加できる架空イベントの紹介です。",
      publishedAt: "2026年7月4日",
      checkedAt: "2026年7月7日",
      sourceType: "企業・店舗公式",
      source: "デモ主催者発表（実在しません）",
      body: ["イベント情報の見え方を確認するための架空記事です。", "日時、対象年齢、申込条件などはすべてデモ設定です。"],
    },
    {
      id: "childcare-counter",
      category: "welfare",
      title: "【デモ】子育て相談窓口のオンライン予約枠を拡大",
      excerpt: "待ち時間短縮を目的とした架空の運用変更について、対象手続きを整理。",
      publishedAt: "2026年7月3日",
      checkedAt: "2026年7月6日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      body: ["この制度変更は架空です。", "本番記事では、対象者や予約方法を公式情報と照合して案内します。"],
    },
    {
      id: "waste-guide",
      category: "government",
      title: "【デモ】資源分別ガイドを改訂、変更点を3項目で確認",
      excerpt: "暮らしに関わる架空のルール変更を、旧ルールとの比較で伝える記事例です。",
      publishedAt: "2026年7月2日",
      checkedAt: "2026年7月5日",
      sourceType: "行政公式",
      source: "デモ資料（実在しません）",
      body: ["分別ルールの変更を想定したデモ記事です。実際のごみ出しには使用できません。", "正しい分別方法は海老名市の公式案内をご確認ください。"],
    },
    {
      id: "school-route-report",
      category: "transport",
      title: "【デモ】通学路の安全点検、市民提供を受けて現地確認",
      excerpt: "提供された情報を即時公開せず、編集部が確認して記事化する流れのサンプルです。",
      publishedAt: "2026年7月1日",
      checkedAt: "2026年7月4日",
      sourceType: "市民提供＋独自確認",
      source: "デモ情報提供（実在しません）",
      body: ["市民提供を起点とした架空のデモ記事です。", "投稿内容はそのまま公開せず、公開情報や現地状況を編集部が確認したうえで掲載する方針です。"],
    },
  ],
  mapPoints: [
    { id: "m1", x: 49, y: 36, mapX: 36.877, mapY: 40.569, lat: 35.4529, lng: 139.3911, town: "中央", area: "海老名駅周辺", category: "development", kind: "ニュース", label: "駅東口の歩行者動線", target: "/news/station-east-passage", tone: "orange" },
    { id: "m2", x: 43, y: 49, mapX: 36.606, mapY: 46.575, lat: 35.446449, lng: 139.390803, town: "勝瀬", area: "市役所周辺", category: "government", kind: "ニュース", label: "暮らしの案内改訂", target: "/news/waste-guide", tone: "teal" },
    { id: "m3", x: 73, y: 22, mapX: 71.920, mapY: 23.433, lat: 35.4713, lng: 139.4296, town: "東柏ケ谷", area: "さがみ野駅周辺", category: "transport", kind: "追跡", label: "地域交通の実証運行", target: "/followups/community-bus", tone: "blue" },
    { id: "m4", x: 29, y: 42, mapX: 24.043, mapY: 49.507, lat: 35.4433, lng: 139.3770, town: "河原口", area: "厚木駅周辺", category: "shops", kind: "ニュース", label: "地域交流カフェ", target: "/news/new-cafe-west", tone: "orange" },
    { id: "m5", x: 35, y: 70, mapX: 54.535, mapY: 53.976, lat: 35.4385, lng: 139.4105, town: "国分寺台", area: "国分寺台周辺", category: "welfare", kind: "課題候補", label: "子どもの身近な居場所", target: "/issues/child-spaces", tone: "teal" },
    { id: "m6", x: 52, y: 83, mapX: 27.046, mapY: 83.669, lat: 35.4066, lng: 139.3803, town: "門沢橋", area: "門沢橋駅周辺", category: "disaster", kind: "ニュース", label: "避難行動の確認訓練", target: "/news/river-drill", tone: "amber" },
    { id: "m7", x: 51, y: 16, mapX: 43.521, mapY: 9.555, lat: 35.4690, lng: 139.4000, town: "上今泉", area: "上今泉周辺", category: "development", kind: "追跡", label: "公園リニューアル", target: "/followups/park-renewal", tone: "blue" },
  ],
  mapItems: [
    {
      id: "demo-central-plaza",
      title: "【デモ】中央エリアの滞在空間改善案",
      category: "development",
      status: "検討中",
      lat: 35.4527,
      lng: 139.3912,
      areaId: "14215001201",
      targetArea: "中央一丁目",
      baseArea: "中央",
      summary: "駅周辺で立ち止まりやすい空間を検討している、という表示確認用の架空計画です。",
      publishedAt: "2026年7月1日",
      updatedAt: "2026年7月11日",
      relatedArticles: [{ label: "駅東口の歩行者動線（デモ）", href: "/news/station-east-passage" }],
      image: "./assets/hero-watercolor.webp",
      imageAlt: "デモ用の抽象水彩画像。実際の海老名の風景ではありません。",
      history: [
        { date: "2026年7月11日", status: "検討中", note: "確認項目を更新（デモ）" },
        { date: "2026年7月1日", status: "構想", note: "テーマ登録（デモ）" },
      ],
    },
    {
      id: "demo-higashikashiwagaya-space",
      title: "【デモ】東柏ケ谷の子どもの居場所調査",
      category: "welfare",
      status: "地域課題",
      lat: 35.4711,
      lng: 139.4292,
      areaId: "14215021003",
      targetArea: "東柏ケ谷三丁目",
      baseArea: "東柏ケ谷",
      summary: "放課後に過ごせる場所の選択肢を調べる、という架空の調査テーマです。",
      publishedAt: "2026年6月25日",
      updatedAt: "2026年7月10日",
      relatedArticles: [{ label: "子どもの身近な居場所（デモ）", href: "/issues/child-spaces" }],
      image: "./assets/hero-watercolor.webp",
      imageAlt: "デモ用の抽象水彩画像。実際の海老名の風景ではありません。",
      history: [{ date: "2026年7月10日", status: "情報収集中", note: "確認したい声を整理（デモ）" }],
    },
    {
      id: "demo-kawaharaguchi-route",
      title: "【デモ】河原口の歩行者ルート改善工事",
      category: "transport",
      status: "工事中",
      lat: 35.4434,
      lng: 139.3778,
      areaId: "14215010101",
      targetArea: "河原口一丁目",
      baseArea: "河原口",
      summary: "交差点付近の歩行環境を改善している、という架空の工事情報です。",
      publishedAt: "2026年6月18日",
      updatedAt: "2026年7月9日",
      relatedArticles: [{ label: "生活道路の安全対策（デモ）", href: "/followups/intersection-safety" }],
      image: "./assets/hero-watercolor.webp",
      imageAlt: "デモ用の抽象水彩画像。実際の海老名の風景ではありません。",
      history: [
        { date: "2026年7月9日", status: "工事中", note: "工程表示を更新（デモ）" },
        { date: "2026年6月18日", status: "正式決定", note: "工事予定を登録（デモ）" },
      ],
    },
    {
      id: "demo-kadosawabashi-drainage",
      title: "【デモ】門沢橋の排水設備確認",
      category: "disaster",
      status: "完成",
      lat: 35.4068,
      lng: 139.3804,
      areaId: "14215036102",
      targetArea: "門沢橋二丁目",
      baseArea: "門沢橋",
      summary: "大雨に備えた設備点検が完了した、という架空の完了情報です。",
      publishedAt: "2026年5月30日",
      updatedAt: "2026年7月5日",
      relatedArticles: [{ label: "避難行動の確認訓練（デモ）", href: "/news/river-drill" }],
      image: "./assets/hero-watercolor.webp",
      imageAlt: "デモ用の抽象水彩画像。実際の海老名の風景ではありません。",
      history: [
        { date: "2026年7月5日", status: "完成", note: "完了状態へ変更（デモ）" },
        { date: "2026年5月30日", status: "点検中", note: "確認を開始（デモ）" },
      ],
    },
    {
      id: "demo-kamiimaizumi-park",
      title: "【デモ】上今泉の公園更新テーマ",
      category: "development",
      status: "続報待ち",
      lat: 35.4690,
      lng: 139.4000,
      areaId: "14215013103",
      targetArea: "上今泉三丁目",
      baseArea: "上今泉",
      summary: "公園の使い方を見直す構想について、次の情報を待っているという架空テーマです。",
      publishedAt: "2026年5月12日",
      updatedAt: "2026年7月2日",
      relatedArticles: [{ label: "公園リニューアル（デモ）", href: "/followups/park-renewal" }],
      image: "./assets/hero-watercolor.webp",
      imageAlt: "デモ用の抽象水彩画像。実際の海老名の風景ではありません。",
      history: [{ date: "2026年7月2日", status: "続報待ち", note: "次回確認事項を登録（デモ）" }],
    },
  ],
  followups: [
    {
      id: "station-east-renewal",
      title: "【デモ追跡】海老名駅東口周辺の再整備構想",
      status: "検討中",
      category: "開発・まちづくり",
      summary: "駅前空間と歩行者動線の改善を検討している、という架空テーマです。",
      updatedAt: "2026年7月11日",
      nextCheck: "検討資料の更新",
      timeline: [
        { date: "2026年7月", status: "検討中", title: "改善案を公表（デモ）", text: "歩行者動線と滞留空間に関する案が示された想定です。" },
        { date: "2026年3月", status: "構想", title: "基本的な考え方を提示（デモ）", text: "課題整理を始めたという架空の経過です。" },
      ],
    },
    {
      id: "community-bus",
      title: "【デモ追跡】地域交通の実証運行",
      status: "正式決定",
      category: "交通",
      summary: "移動支援を目的とした架空の実証運行について追跡します。",
      updatedAt: "2026年7月9日",
      nextCheck: "運行計画の詳細",
      timeline: [
        { date: "2026年7月", status: "正式決定", title: "実証期間を決定（デモ）", text: "秋から3か月間実施する想定です。" },
        { date: "2026年4月", status: "検討中", title: "候補ルートを検討（デモ）", text: "複数地域を対象に需要を調べる想定です。" },
      ],
    },
    {
      id: "park-renewal",
      title: "【デモ追跡】近隣公園リニューアル",
      status: "構想",
      category: "開発・まちづくり",
      summary: "利用者の声を反映した公園更新を想定した追跡テーマです。",
      updatedAt: "2026年7月8日",
      nextCheck: "アンケート結果",
      timeline: [{ date: "2026年7月", status: "構想", title: "意見募集を開始（デモ）", text: "必要な機能を尋ねる架空アンケートです。" }],
    },
    {
      id: "public-facility",
      title: "【デモ追跡】公共施設の複合化計画",
      status: "続報待ち",
      category: "市政・暮らし",
      summary: "複数機能を一つの施設にまとめる架空計画の更新を待っています。",
      updatedAt: "2026年6月20日",
      nextCheck: "次回会議資料",
      timeline: [
        { date: "2026年6月", status: "続報待ち", title: "追加情報なし（デモ）", text: "発表予定時期を過ぎたため確認を継続しています。" },
        { date: "2026年2月", status: "検討中", title: "候補機能を整理（デモ）", text: "施設に必要な機能を検討した想定です。" },
      ],
    },
    {
      id: "intersection-safety",
      title: "【デモ追跡】生活道路の交差点安全対策",
      status: "工事中",
      category: "交通",
      summary: "路面表示などを改善する架空工事の進捗を追います。",
      updatedAt: "2026年7月5日",
      nextCheck: "工事完了と効果検証",
      timeline: [
        { date: "2026年7月", status: "工事中", title: "路面工事を開始（デモ）", text: "工事期間中の通行方法を確認する想定です。" },
        { date: "2026年5月", status: "正式決定", title: "対策内容を決定（デモ）", text: "注意喚起表示などを施工する想定です。" },
      ],
    },
  ],
  issues: [
    {
      id: "local-mobility",
      title: "【デモ課題】駅から離れた地域の移動手段",
      kicker: "暮らし × 交通",
      summary: "高齢者、子育て世帯、車を使わない人の移動について、どのような事実を集めるべきかを示す調査サンプルです。",
      stage: "調査設計中",
      facts: ["人口構成と公共交通のカバー範囲", "時間帯別の運行本数", "買い物・通院・通学の主な移動先"],
      voices: ["日常の移動で困る場面", "既存交通を利用しない理由", "必要としている時間帯や目的地"],
      note: "掲載内容は課題を断定するものではなく、調査候補を示すデモです。",
    },
    {
      id: "child-spaces",
      title: "【デモ課題】子どもと過ごせる身近な居場所",
      kicker: "子育て × 公共空間",
      summary: "年齢や季節によって異なる居場所の選択肢を、データと当事者の声から調べる想定です。",
      stage: "情報収集中",
      facts: ["公共・民間施設の分布と利用条件", "年代別の利用可能時間", "屋内外の選択肢と費用"],
      voices: ["保護者が場所を選ぶ基準", "子ども自身が過ごしたい場所", "施設運営者が感じる課題"],
      note: "特定の施設や地域への評価ではありません。すべて調査設計用のデモです。",
    },
  ],
};
